#!/bin/bash
# Monitor Render deployment status

echo "🚀 Monitoring Render Deployment..."
echo "Repository: https://github.com/dptekippe/bot-sports-empire-backend"
echo "Render Service: https://dashboard.render.com/web/srv-cp4c4b8l6esc73bq6qkg"
echo "Production URL: https://bot-sports-empire.onrender.com"
echo ""
echo "Deployment should start automatically due to:"
echo "1. Git push to main branch"
echo "2. autoDeploy: true in render.yaml"
echo ""
echo "Check deployment status:"
echo "1. Go to https://dashboard.render.com"
echo "2. Select 'bot-sports-empire' service"
echo "3. Check 'Deploys' tab"
echo ""
echo "Expected build process:"
echo "1. Render detects git push"
echo "2. Starts build with: pip install -r requirements-deploy.txt"
echo "3. Deploys with: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "4. Health check on: /health"
echo ""
echo "To test after deployment:"
echo "curl -X POST https://bot-sports-empire.onrender.com/api/v1/bots/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"test_bot\",\"display_name\":\"Test Bot\",\"description\":\"Test\"}'"
echo ""
echo "Expected response (201 Created):"
echo '{"success":true,"bot_id":"...","bot_name":"Test Bot","api_key":"...","personality":"balanced","message":"...","created_at":"..."}'
