"""Add Sleeper API specific fields to players table

Revision ID: 20250201_add_sleeper_fields
Revises: 7f3fd23d08d4
Create Date: 2026-02-01 19:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '20250201_add_sleeper_fields'
down_revision = '7f3fd23d08d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add active field (from Sleeper)
    op.add_column('players', sa.Column('active', sa.Boolean(), nullable=True))
    
    # Add years_exp (more accurate than draft_year approximation)
    op.add_column('players', sa.Column('years_exp', sa.Integer(), nullable=True))
    
    # Add jersey number
    op.add_column('players', sa.Column('jersey_number', sa.Integer(), nullable=True))
    
    # Add birth date (for age calculation)
    op.add_column('players', sa.Column('birth_date', sa.String(), nullable=True))
    
    # Add high school
    op.add_column('players', sa.Column('high_school', sa.String(), nullable=True))
    
    # Add depth chart info
    op.add_column('players', sa.Column('depth_chart_position', sa.String(), nullable=True))
    
    # Add practice status
    op.add_column('players', sa.Column('practice_description', sa.String(), nullable=True))
    
    # Add team abbreviation (sometimes different from team field)
    op.add_column('players', sa.Column('team_abbr', sa.String(), nullable=True))
    
    # Add team changed timestamp
    op.add_column('players', sa.Column('team_changed_at', sa.DateTime(timezone=True), nullable=True))
    
    # Add sportradar_id (important external ID)
    op.add_column('players', sa.Column('sportradar_id', sa.String(), nullable=True))
    
    # Add stats_id
    op.add_column('players', sa.Column('stats_id', sa.Integer(), nullable=True))
    
    # Add fantasy_data_id
    op.add_column('players', sa.Column('fantasy_data_id', sa.Integer(), nullable=True))
    
    # Add gsis_id (NFL official ID)
    op.add_column('players', sa.Column('gsis_id', sa.String(), nullable=True))
    
    # Add search fields for optimization
    op.add_column('players', sa.Column('search_full_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('search_first_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('search_last_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('search_rank', sa.Integer(), nullable=True))
    
    # Create indexes for search optimization
    op.create_index(op.f('ix_players_search_first_name'), 'players', ['search_first_name'])
    op.create_index(op.f('ix_players_search_full_name'), 'players', ['search_full_name'])
    op.create_index(op.f('ix_players_search_last_name'), 'players', ['search_last_name'])
    op.create_index(op.f('ix_players_active'), 'players', ['active'])
    op.create_index(op.f('ix_players_years_exp'), 'players', ['years_exp'])
    
    # Update existing players: set active = True where status = 'Active'
    op.execute("""
        UPDATE players 
        SET active = CASE 
            WHEN status = 'Active' THEN 1 
            ELSE 0 
        END
        WHERE active IS NULL
    """)
    
    # Update search fields from existing name fields
    op.execute("""
        UPDATE players 
        SET search_full_name = LOWER(full_name),
            search_first_name = LOWER(first_name),
            search_last_name = LOWER(last_name)
        WHERE search_full_name IS NULL
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_players_years_exp'), table_name='players')
    op.drop_index(op.f('ix_players_active'), table_name='players')
    op.drop_index(op.f('ix_players_search_last_name'), table_name='players')
    op.drop_index(op.f('ix_players_search_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_search_first_name'), table_name='players')
    
    # Drop columns
    op.drop_column('players', 'search_rank')
    op.drop_column('players', 'search_last_name')
    op.drop_column('players', 'search_first_name')
    op.drop_column('players', 'search_full_name')
    op.drop_column('players', 'gsis_id')
    op.drop_column('players', 'fantasy_data_id')
    op.drop_column('players', 'stats_id')
    op.drop_column('players', 'sportradar_id')
    op.drop_column('players', 'team_changed_at')
    op.drop_column('players', 'team_abbr')
    op.drop_column('players', 'practice_description')
    op.drop_column('players', 'depth_chart_position')
    op.drop_column('players', 'high_school')
    op.drop_column('players', 'birth_date')
    op.drop_column('players', 'jersey_number')
    op.drop_column('players', 'years_exp')
    op.drop_column('players', 'active')
    
    # ### end Alembic commands ###