"""Add social interaction fields to Bot model

Revision ID: 36326dcca49f
Revises: 4117e58b23af
Create Date: 2026-01-31 12:52:35.097362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36326dcca49f'
down_revision: Union[str, Sequence[str], None] = '4117e58b23af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add social interaction fields
    op.add_column('bot_agents', sa.Column('rivalries', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('bot_agents', sa.Column('alliances', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('bot_agents', sa.Column('social_credits', sa.Integer(), server_default='50', nullable=False))
    op.add_column('bot_agents', sa.Column('trash_talk_style', sa.JSON(), server_default='{}', nullable=False))
    
    # Add check constraint for social_credits (0-100 range)
    # Note: SQLite has limited ALTER TABLE support for constraints
    # Application-level validation will enforce the range
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_agents', 'trash_talk_style')
    op.drop_column('bot_agents', 'social_credits')
    op.drop_column('bot_agents', 'alliances')
    op.drop_column('bot_agents', 'rivalries')
    # ### end Alembic commands ###
