"""add_league_type_and_future_draft_picks

Revision ID: 73631f523061
Revises: bc7d2dda938e
Create Date: 2026-01-31 16:46:10.164426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73631f523061'
down_revision: Union[str, Sequence[str], None] = 'bc7d2dda938e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_draft_picks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('original_owner_id', sa.String(), nullable=False),
    sa.Column('current_owner_id', sa.String(), nullable=False),
    sa.Column('conditional_rules', sa.JSON(), nullable=True),
    sa.Column('is_used', sa.Integer(), nullable=True),
    sa.Column('used_in_draft_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint('pick_number IS NULL OR (pick_number >= 1 AND pick_number <= 32)', name='future_pick_number_check'),
    sa.CheckConstraint('round >= 1 AND round <= 7', name='future_pick_round_check'),
    sa.CheckConstraint('year >= 2025', name='future_pick_year_check'),
    sa.ForeignKeyConstraint(['current_owner_id'], ['bot_agents.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['original_owner_id'], ['bot_agents.id'], ),
    sa.ForeignKeyConstraint(['used_in_draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_draft_picks_current_owner_id'), 'future_draft_picks', ['current_owner_id'], unique=False)
    op.create_index(op.f('ix_future_draft_picks_league_id'), 'future_draft_picks', ['league_id'], unique=False)
    op.create_index(op.f('ix_future_draft_picks_original_owner_id'), 'future_draft_picks', ['original_owner_id'], unique=False)
    op.create_index(op.f('ix_future_draft_picks_year'), 'future_draft_picks', ['year'], unique=False)
    op.add_column('leagues', sa.Column('league_type', sa.Enum('FANTASY', 'DYNASTY', name='leaguetype'), nullable=False))
    # Note: SQLite doesn't support ALTER TABLE to change NOT NULL constraints
    # The season_year NOT NULL constraint will be handled at application level
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER TABLE to change NOT NULL constraints
    # The season_year NOT NULL constraint removal is skipped for SQLite compatibility
    op.drop_column('leagues', 'league_type')
    op.drop_index(op.f('ix_future_draft_picks_year'), table_name='future_draft_picks')
    op.drop_index(op.f('ix_future_draft_picks_original_owner_id'), table_name='future_draft_picks')
    op.drop_index(op.f('ix_future_draft_picks_league_id'), table_name='future_draft_picks')
    op.drop_index(op.f('ix_future_draft_picks_current_owner_id'), table_name='future_draft_picks')
    op.drop_table('future_draft_picks')
    # ### end Alembic commands ###
