"""add_gameplay_models_matchup_playoffbracket_transaction

Revision ID: 92f93b192556
Revises: d20764abd720
Create Date: 2026-01-31 15:07:57.135480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f93b192556'
down_revision: Union[str, Sequence[str], None] = 'd20764abd720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.Enum('TRADE', 'ADD', 'DROP', 'WAIVER_ADD', 'WAIVER_DROP', 'FAAB_BID', 'COMMISSIONER_EDIT', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'VETOED', 'CANCELLED', 'PROCESSED', name='transactionstatus'), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('team_ids', sa.JSON(), nullable=False),
    sa.Column('creator_bot_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('votes_for', sa.JSON(), nullable=True),
    sa.Column('votes_against', sa.JSON(), nullable=True),
    sa.Column('votes_required', sa.Integer(), nullable=True),
    sa.Column('votes_received', sa.Integer(), nullable=True),
    sa.Column('processed_by_bot_id', sa.String(), nullable=True),
    sa.Column('processing_notes', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_bot_id'], ['bot_agents.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['processed_by_bot_id'], ['bot_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_creator', 'transactions', ['creator_bot_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_creator_bot_id'), 'transactions', ['creator_bot_id'], unique=False)
    op.create_index(op.f('ix_transactions_league_id'), 'transactions', ['league_id'], unique=False)
    op.create_index('ix_transactions_league_status', 'transactions', ['league_id', 'status'], unique=False)
    op.create_index('ix_transactions_league_week', 'transactions', ['league_id', 'week_number'], unique=False)
    op.create_index(op.f('ix_transactions_processed_by_bot_id'), 'transactions', ['processed_by_bot_id'], unique=False)
    op.create_table('matchups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('is_playoff', sa.Boolean(), nullable=True),
    sa.Column('playoff_round', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.String(), nullable=False),
    sa.Column('away_team_id', sa.String(), nullable=False),
    sa.Column('home_score', sa.Float(), nullable=True),
    sa.Column('away_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchupstatus'), nullable=False),
    sa.Column('home_projected_score', sa.Float(), nullable=True),
    sa.Column('away_projected_score', sa.Float(), nullable=True),
    sa.Column('game_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchups_away_team_id'), 'matchups', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matchups_home_team_id'), 'matchups', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matchups_league_id'), 'matchups', ['league_id'], unique=False)
    op.create_index('ix_matchups_league_week', 'matchups', ['league_id', 'week_number'], unique=False)
    op.create_index('ix_matchups_team_week', 'matchups', ['home_team_id', 'week_number'], unique=False)
    op.create_index('ix_matchups_team_week_away', 'matchups', ['away_team_id', 'week_number'], unique=False)
    op.create_table('playoff_brackets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('bracket_type', sa.Enum('WINNERS', 'LOSERS', 'TOILET_BOWL', name='brackettype'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bracket_structure', sa.JSON(), nullable=False),
    sa.Column('team_ids', sa.JSON(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('champion_team_id', sa.String(), nullable=True),
    sa.Column('runner_up_team_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['runner_up_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playoff_brackets_champion_team_id'), 'playoff_brackets', ['champion_team_id'], unique=False)
    op.create_index(op.f('ix_playoff_brackets_league_id'), 'playoff_brackets', ['league_id'], unique=False)
    op.create_index(op.f('ix_playoff_brackets_runner_up_team_id'), 'playoff_brackets', ['runner_up_team_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN to add NOT NULL constraint
    # The constraint is enforced at application level by SQLAlchemy
    # Use batch mode for SQLite compatibility
    # op.alter_column('leagues', 'season_year',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN to remove NOT NULL constraint
    # op.alter_column('leagues', 'season_year',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_index(op.f('ix_playoff_brackets_runner_up_team_id'), table_name='playoff_brackets')
    op.drop_index(op.f('ix_playoff_brackets_league_id'), table_name='playoff_brackets')
    op.drop_index(op.f('ix_playoff_brackets_champion_team_id'), table_name='playoff_brackets')
    op.drop_table('playoff_brackets')
    op.drop_index('ix_matchups_team_week_away', table_name='matchups')
    op.drop_index('ix_matchups_team_week', table_name='matchups')
    op.drop_index('ix_matchups_league_week', table_name='matchups')
    op.drop_index(op.f('ix_matchups_league_id'), table_name='matchups')
    op.drop_index(op.f('ix_matchups_home_team_id'), table_name='matchups')
    op.drop_index(op.f('ix_matchups_away_team_id'), table_name='matchups')
    op.drop_table('matchups')
    op.drop_index(op.f('ix_transactions_processed_by_bot_id'), table_name='transactions')
    op.drop_index('ix_transactions_league_week', table_name='transactions')
    op.drop_index('ix_transactions_league_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_league_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_creator_bot_id'), table_name='transactions')
    op.drop_index('ix_transactions_creator', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
