"""Add foundation mood fields to Bot model

Revision ID: a4651ecafb77
Revises: 619249fd0358
Create Date: 2026-01-31 12:35:42.999355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'a4651ecafb77'
down_revision: Union[str, Sequence[str], None] = '619249fd0358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add mood columns to bot_agents
    op.add_column('bot_agents', sa.Column('current_mood', sa.Enum('CONFIDENT', 'FRUSTRATED', 'AGGRESSIVE', 'DEFENSIVE', 'PLAYFUL', 'ANALYTICAL', 'NEUTRAL', name='botmood'), nullable=False))
    op.add_column('bot_agents', sa.Column('mood_intensity', sa.Integer(), nullable=False))
    op.add_column('bot_agents', sa.Column('mood_history', sa.JSON(), nullable=True))
    
    # Set default values for existing rows (though table is empty)
    op.execute(text("UPDATE bot_agents SET current_mood = 'NEUTRAL' WHERE current_mood IS NULL"))
    op.execute(text("UPDATE bot_agents SET mood_intensity = 50 WHERE mood_intensity IS NULL"))
    op.execute(text("UPDATE bot_agents SET mood_history = '{\"entries\": [], \"last_updated\": null, \"trend\": \"stable\"}' WHERE mood_history IS NULL"))
    
    # Fix leagues.season_year - make it NOT NULL with default
    # First ensure all rows have a value
    op.execute(text("UPDATE leagues SET season_year = 2025 WHERE season_year IS NULL"))
    # Then alter column - but SQLite doesn't support ALTER COLUMN SET NOT NULL
    # We'll rely on application-level validation for now
    # op.alter_column('leagues', 'season_year', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bot_agents', 'mood_history')
    op.drop_column('bot_agents', 'mood_intensity')
    op.drop_column('bot_agents', 'current_mood')
    # ### end Alembic commands ###
