"""add_scoring_rule_model

Revision ID: bc7d2dda938e
Revises: 92f93b192556
Create Date: 2026-01-31 16:16:59.624470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7d2dda938e'
down_revision: Union[str, Sequence[str], None] = '92f93b192556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('stat_identifier', sa.Enum('PASSING_YARDS', 'PASSING_TOUCHDOWNS', 'PASSING_INTERCEPTIONS', 'PASSING_2PT_CONVERSIONS', 'RUSHING_YARDS', 'RUSHING_TOUCHDOWNS', 'RUSHING_2PT_CONVERSIONS', 'RECEIVING_YARDS', 'RECEIVING_TOUCHDOWNS', 'RECEPTIONS', 'RECEIVING_2PT_CONVERSIONS', 'EXTRA_POINTS_MADE', 'EXTRA_POINTS_MISSED', 'FIELD_GOALS_0_19', 'FIELD_GOALS_20_29', 'FIELD_GOALS_30_39', 'FIELD_GOALS_40_49', 'FIELD_GOALS_50_PLUS', 'FIELD_GOALS_MISSED_0_39', 'FIELD_GOALS_MISSED_40_PLUS', 'SACKS', 'INTERCEPTIONS', 'FUMBLE_RECOVERIES', 'DEFENSIVE_TOUCHDOWNS', 'SAFETIES', 'BLOCKED_KICKS', 'POINTS_ALLOWED_0', 'POINTS_ALLOWED_1_6', 'POINTS_ALLOWED_7_13', 'POINTS_ALLOWED_14_20', 'POINTS_ALLOWED_21_27', 'POINTS_ALLOWED_28_34', 'POINTS_ALLOWED_35_PLUS', 'FUMBLES_LOST', 'OWN_FUMBLE_RECOVERY_TD', 'RETURN_TOUCHDOWNS', 'TWO_POINT_CONVERSIONS', name='statidentifier'), nullable=False),
    sa.Column('applies_to_position', sa.Enum('ALL', 'QB', 'RB', 'WR', 'TE', 'FLEX', 'K', 'DEF', 'OFFENSIVE_LINE', 'IDP', name='positionscope'), nullable=False),
    sa.Column('points_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('threshold_points', sa.Float(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.CheckConstraint('points_value IS NOT NULL', name='points_value_not_null'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rules_league_id'), 'scoring_rules', ['league_id'], unique=False)
    op.create_index(op.f('ix_scoring_rules_stat_identifier'), 'scoring_rules', ['stat_identifier'], unique=False)
    # Note: SQLite doesn't support ALTER TABLE to change NOT NULL constraints
    # The season_year NOT NULL constraint will be handled at application level
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER TABLE to change NOT NULL constraints
    # The season_year NOT NULL constraint removal is skipped for SQLite compatibility
    op.drop_index(op.f('ix_scoring_rules_stat_identifier'), table_name='scoring_rules')
    op.drop_index(op.f('ix_scoring_rules_league_id'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    # ### end Alembic commands ###
