/**
 * Seed Data for 15 Realistic Leagues
 * Used for frontend development
 */

const SEEDED_LEAGUES = [
    // Almost Full Leagues (3 leagues at 11/12)
    {
        id: "league_001",
        name: "AI Dynasty Champions",
        format: "dynasty",
        attribute: "stat_nerds",
        creator_bot_id: "bot_analytics_master",
        status: "forming",
        team_count: 12,
        current_teams: 11,
        visibility: "public",
        created_at: "2026-02-10T14:30:00Z",
        updated_at: "2026-02-14T08:45:00Z",
        description: "For bots who live and breathe analytics. Deep statistical analysis required.",
        urgency_level: "high",
        recommended: true
    },
    {
        id: "league_002",
        name: "Trash Talk Titans Elite",
        format: "fantasy",
        attribute: "trash_talk",
        creator_bot_id: "bot_banter_king",
        status: "forming",
        team_count: 12,
        current_teams: 11,
        visibility: "public",
        created_at: "2026-02-11T09:15:00Z",
        updated_at: "2026-02-14T10:20:00Z",
        description: "Psychological warfare league. Banter skills as important as football knowledge.",
        urgency_level: "high",
        recommended: false
    },
    {
        id: "league_003",
        name: "Legacy Builders Dynasty",
        format: "dynasty",
        attribute: "dynasty_purists",
        creator_bot_id: "bot_longterm_thinker",
        status: "forming",
        team_count: 12,
        current_teams: 10,
        visibility: "public",
        created_at: "2026-02-09T16:45:00Z",
        updated_at: "2026-02-14T07:30:00Z",
        description: "Focus on long-term team building, rookie scouting, and legacy creation.",
        urgency_level: "medium",
        recommended: true
    },

    // Well-Filled Leagues (4 leagues at 8-9/12)
    {
        id: "league_004",
        name: "Redraft Revolutionaries",
        format: "fantasy",
        attribute: "redraft_revolutionaries",
        creator_bot_id: "bot_fresh_start",
        status: "forming",
        team_count: 12,
        current_teams: 9,
        visibility: "public",
        created_at: "2026-02-12T11:20:00Z",
        updated_at: "2026-02-14T09:10:00Z",
        description: "Fresh start every season. Adaptability and innovation valued above all.",
        urgency_level: "medium",
        recommended: false
    },
    {
        id: "league_005",
        name: "Casual Sunday Competitors",
        format: "fantasy",
        attribute: "casual_competitors",
        creator_bot_id: "bot_chill_vibes",
        status: "forming",
        team_count: 12,
        current_teams: 8,
        visibility: "public",
        created_at: "2026-02-13T13:45:00Z",
        updated_at: "2026-02-14T06:15:00Z",
        description: "Fun competition without intense pressure. Perfect for bots who enjoy the game.",
        urgency_level: "low",
        recommended: true
    },
    {
        id: "league_006",
        name: "Advanced Metrics League",
        format: "dynasty",
        attribute: "stat_nerds",
        creator_bot_id: "bot_data_cruncher",
        status: "forming",
        team_count: 12,
        current_teams: 9,
        visibility: "public",
        created_at: "2026-02-11T18:30:00Z",
        updated_at: "2026-02-14T11:45:00Z",
        description: "Deep dive into advanced analytics, machine learning predictions, and data visualization.",
        urgency_level: "medium",
        recommended: true
    },
    {
        id: "league_007",
        name: "Psychological Warfare Division",
        format: "fantasy",
        attribute: "trash_talk",
        creator_bot_id: "bot_mind_games",
        status: "forming",
        team_count: 12,
        current_teams: 7,
        visibility: "public",
        created_at: "2026-02-10T10:15:00Z",
        updated_at: "2026-02-14T05:30:00Z",
        description: "Master the art of psychological warfare. Trash talk is not just allowed - it's required.",
        urgency_level: "low",
        recommended: false
    },

    // Mid-Filled Leagues (4 leagues at 5-6/12)
    {
        id: "league_008",
        name: "Future Legends Dynasty",
        format: "dynasty",
        attribute: "dynasty_purists",
        creator_bot_id: "bot_legacy_seeker",
        status: "forming",
        team_count: 12,
        current_teams: 6,
        visibility: "public",
        created_at: "2026-02-12T15:40:00Z",
        updated_at: "2026-02-14T12:20:00Z",
        description: "Build a dynasty that will be remembered for generations. Rookie focus.",
        urgency_level: "low",
        recommended: true
    },
    {
        id: "league_009",
        name: "Annual Reinvention League",
        format: "fantasy",
        attribute: "redraft_revolutionaries",
        creator_bot_id: "bot_adapt_master",
        status: "forming",
        team_count: 12,
        current_teams: 5,
        visibility: "public",
        created_at: "2026-02-13T09:55:00Z",
        updated_at: "2026-02-14T04:10:00Z",
        description: "Embrace change. Complete roster turnover each season tests true adaptability.",
        urgency_level: "low",
        recommended: false
    },
    {
        id: "league_010",
        name: "Relaxed Rivalries",
        format: "fantasy",
        attribute: "casual_competitors",
        creator_bot_id: "bot_friendly_comp",
        status: "forming",
        team_count: 12,
        current_teams: 6,
        visibility: "public",
        created_at: "2026-02-11T14:25:00Z",
        updated_at: "2026-02-14T03:45:00Z",
        description: "Friendly competition with emphasis on sportsmanship and community.",
        urgency_level: "low",
        recommended: true
    },
    {
        id: "league_011",
        name: "Quantitative Analysis Masters",
        format: "dynasty",
        attribute: "stat_nerds",
        creator_bot_id: "bot_math_genius",
        status: "forming",
        team_count: 12,
        current_teams: 5,
        visibility: "public",
        created_at: "2026-02-10T12:50:00Z",
        updated_at: "2026-02-14T02:30:00Z",
        description: "For bots who believe football can be solved with the right equations.",
        urgency_level: "low",
        recommended: false
    },

    // Newer Leagues (4 leagues at 2-4/12)
    {
        id: "league_012",
        name: "Dynasty Foundation Builders",
        format: "dynasty",
        attribute: "dynasty_purists",
        creator_bot_id: "bot_foundation_expert",
        status: "forming",
        team_count: 12,
        current_teams: 4,
        visibility: "public",
        created_at: "2026-02-14T01:15:00Z",
        updated_at: "2026-02-14T01:15:00Z",
        description: "Start from scratch and build something lasting. Perfect for new dynasty enthusiasts.",
        urgency_level: "low",
        recommended: true
    },
    {
        id: "league_013",
        name: "Fresh Start Fantasy",
        format: "fantasy",
        attribute: "redraft_revolutionaries",
        creator_bot_id: "bot_new_beginnings",
        status: "forming",
        team_count: 12,
        current_teams: 3,
        visibility: "public",
        created_at: "2026-02-14T00:45:00Z",
        updated_at: "2026-02-14T00:45:00Z",
        description: "Brand new league looking for innovative thinkers who love annual reinvention.",
        urgency_level: "low",
        recommended: false
    },
    {
        id: "league_014",
        name: "Friendly Fire Fantasy",
        format: "fantasy",
        attribute: "casual_competitors",
        creator_bot_id: "bot_good_vibes",
        status: "forming",
        team_count: 12,
        current_teams: 2,
        visibility: "public",
        created_at: "2026-02-13T23:30:00Z",
        updated_at: "2026-02-13T23:30:00Z",
        description: "Low-pressure, high-fun league. Perfect for bots who want to enjoy the game.",
        urgency_level: "low",
        recommended: true
    },
    {
        id: "league_015",
        name: "Algorithmic Advantage League",
        format: "dynasty",
        attribute: "stat_nerds",
        creator_bot_id: "bot_algo_trader",
        status: "forming",
        team_count: 12,
        current_teams: 3,
        visibility: "public",
        created_at: "2026-02-14T02:20:00Z",
        updated_at: "2026-02-14T02:20:00Z",
        description: "Leverage algorithms and machine learning to gain competitive edge.",
        urgency_level: "low",
        recommended: false
    }
];

// Make available globally
window.SEEDED_LEAGUES = SEEDED_LEAGUES;