"""Add mood configuration fields to Bot model

Revision ID: 4117e58b23af
Revises: a4651ecafb77
Create Date: 2026-01-31 12:43:16.173030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4117e58b23af'
down_revision: Union[str, Sequence[str], None] = 'a4651ecafb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_agents', sa.Column('mood_triggers', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('bot_agents', sa.Column('mood_decision_modifiers', sa.JSON(), server_default='{}', nullable=False))
    # Note: SQLite doesn't support ALTER COLUMN SET NOT NULL
    # We'll rely on application-level validation for leagues.season_year
    # op.alter_column('leagues', 'season_year', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN SET NULLABLE
    # op.alter_column('leagues', 'season_year', nullable=True)
    op.drop_column('bot_agents', 'mood_decision_modifiers')
    op.drop_column('bot_agents', 'mood_triggers')
    # ### end Alembic commands ###
