"""Remove test_column from Player model

Revision ID: 65554274c4d3
Revises: 7b6a7de82b81
Create Date: 2026-01-31 11:50:46.309259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65554274c4d3'
down_revision: Union[str, Sequence[str], None] = '7b6a7de82b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('test_column', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
