"""add_dynasty_fields_to_league_settings

Revision ID: 7f3fd23d08d4
Revises: veto_voting_system
Create Date: 2026-01-31 23:40:38.583655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3fd23d08d4'
down_revision: Union[str, Sequence[str], None] = 'veto_voting_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add dynasty-specific fields to league_settings table
    # Note: SQLite doesn't support adding CHECK constraints after table creation
    # We'll handle constraints at the application level in the model
    op.add_column('league_settings', sa.Column('max_keepers', sa.Integer(), nullable=True))
    op.add_column('league_settings', sa.Column('taxi_squad_size', sa.Integer(), nullable=True))
    op.add_column('league_settings', sa.Column('future_pick_trading_enabled', sa.Boolean(), nullable=True))
    op.add_column('league_settings', sa.Column('rookie_draft_enabled', sa.Boolean(), nullable=True))
    op.add_column('league_settings', sa.Column('startup_draft_type', sa.String(), nullable=True))
    op.add_column('league_settings', sa.Column('rookie_draft_type', sa.String(), nullable=True))
    op.add_column('league_settings', sa.Column('keeper_deadline_week', sa.Integer(), nullable=True))
    op.add_column('league_settings', sa.Column('ir_slots', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    # Note: For SQLite, we need to handle defaults at application level
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns
    op.drop_column('league_settings', 'ir_slots')
    op.drop_column('league_settings', 'keeper_deadline_week')
    op.drop_column('league_settings', 'rookie_draft_type')
    op.drop_column('league_settings', 'startup_draft_type')
    op.drop_column('league_settings', 'rookie_draft_enabled')
    op.drop_column('league_settings', 'future_pick_trading_enabled')
    op.drop_column('league_settings', 'taxi_squad_size')
    op.drop_column('league_settings', 'max_keepers')
    # ### end Alembic commands ###
