"""Add test_column to Player model

Revision ID: 7b6a7de82b81
Revises: 1da4e07543ce
Create Date: 2026-01-31 11:50:16.288763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6a7de82b81'
down_revision: Union[str, Sequence[str], None] = '1da4e07543ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('test_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'test_column')
    # ### end Alembic commands ###
